creacion clases closes #1 #2
quintanamartin/project-2-kindle-bueno pull request #12
Opened 2019-08-18 21:42 UTC by srmaikol

2019-08-19 21:54 UTC, carigonz requested changes

2019-08-19 21:54 UTC, carigonz commented on kindle.js
> +		}
te falta setear segun corresponda `_current` o `_next`

2019-08-19 22:09 UTC, srmaikol commented on kindle.js
> +		}
listo, ya commitee tu agregado

2019-08-19 22:51 UTC, carigonz commented on kindle.js
> +}
chequea que te falta cerrar el corchete de la clase al final

2019-08-20 02:39 UTC, srmaikol commented on kindle.js
> +}
seré curioso, cómo detectás esos errores?

2019-08-20 03:54 UTC, carigonz approved these changes

2019-08-20 03:54 UTC, merged