filterBy added
quintanamartin/project-2-kindle-bueno pull request #17
Opened 2019-08-29 14:11 UTC by leotocca

2019-08-29 17:08 UTC, carigonz requested changes
@leotocca el codigo no anda, te dejo la consigna

> .filterBy(criteria): retorna un array de los eBooks ya leídos o bo leídos aún, según si se recibe el string 'read' o 'unread' como parámetro

el codigo no tiene sentido, estas comparado un booleano contra 'read' o 'unread' este código siempre retorna un array vacio
`return this._library.filter(x => x.read === criteria);`

deberias armar alguna funcion privada que construya un array o un objeto, el cual a su vez contenga todos los eBooks(en objetos) que hayan sido leidos o no y despues el filterBy deberia retornar el array segun corresponda. Ademas, estaria bueno agregar un else por si no filtran por 'read' o 'unread' que diga que solo puede filtrar por esos criterios. Si estas trabado mandame un slack y lo vemos

2019-08-31 19:31 UTC, leotocca commented
@carigonz Ya corregi el filterBy. Ahora toma como parametros "read" o "unread" y retorna un array filtrado sin las propiedad "read" y "readDate".

2019-08-31 23:47 UTC, carigonz requested changes

2019-08-31 23:47 UTC, carigonz commented on kindle.js
>  	}
esta es la función mal escrita, seria lo mismo pero con un `.filter` que borra las dos ultimas propiedades

2019-08-31 23:47 UTC, carigonz commented on kindle.js
> +			return console.log('You have no items that match the selected filters');
@leotocca en si el codigo esta bien, y funciona. 
El problema es que segun lo que dijo nico en el slack, debería tomar el array desde `.library`, propiedad publica, en vez de desde `._library` .
esto lleva a que hay otro error que te lo voy a marcar en este PR asi lo solucionas todo en uno, el getter de .library está mal escrito, ya que deberia retornar un array sin las propiedades `.read` y la de `.readDate`, de este modo el codigo va a quedar más legible, pero primero hay que modificar get library.

2019-09-06 00:57 UTC, carigonz commented
@leotocca no mire el codigo, pero tenes que resolvir los merge conflicts

2019-09-06 01:05 UTC, carigonz approved these changes

2019-09-06 01:06 UTC, carigonz commented
El codigo funciona perfecto, resolve el merge conflict y mergeamos !

2019-09-08 22:23 UTC, merged